### ISSUE TITLE
Bash Support Pro does not work with WebStorm 2021.3

### ISSUE THREAD

**Issue by mrbscreen** [BashSupport-Pro/bashsupport-pro#92]
After upgrading WebStorm from 2021.3 RC to 2021.3 the IDE does not start correctly.
Deactivating BashSupport Pro solve the issue.

In the log one can find the following error / stack trace:
```
2021-11-29 16:49:08,919 [  90856]  ERROR - llij.ide.plugins.PluginManager - com/intellij/application/options/IndentOptionsEditorBase 
java.lang.NoClassDefFoundError: com/intellij/application/options/IndentOptionsEditorBase
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3307)
	at java.base/java.lang.Class.getMethod0(Class.java:3293)
	at java.base/java.lang.Class.getMethod(Class.java:2106)
	at com.intellij.psi.codeStyle.LanguageCodeStyleSettingsProvider.registerSettingsPageProvider(LanguageCodeStyleSettingsProvider.java:405)
	at com.intellij.psi.codeStyle.LanguageCodeStyleSettingsProvider.calcSettingPagesProviders(LanguageCodeStyleSettingsProvider.java:386)
	at com.intellij.psi.codeStyle.LanguageCodeStyleSettingsProvider.lambda$getSettingsPagesProviders$2(LanguageCodeStyleSettingsProvider.java:379)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:209)
	at com.intellij.psi.codeStyle.LanguageCodeStyleSettingsProvider.getSettingsPagesProviders(LanguageCodeStyleSettingsProvider.java:379)
	at com.intellij.psi.codeStyle.CodeStyleSettingsServiceImpl.getCustomCodeStyleSettingsFactories(CodeStyleSettingsServiceImpl.java:64)
	at com.intellij.psi.codeStyle.CustomCodeStyleSettingsManager.initCustomSettings(CustomCodeStyleSettingsManager.java:25)
	at com.intellij.psi.codeStyle.CodeStyleSettings.<init>(CodeStyleSettings.java:101)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.createSettings(CodeStyleSettingsManager.java:52)
	at com.intellij.psi.codeStyle.ProjectCodeStyleSettingsManager.setMainProjectCodeStyle(ProjectCodeStyleSettingsManager.java:79)
	at com.intellij.psi.codeStyle.ProjectCodeStyleSettingsManager.<init>(ProjectCodeStyleSettingsManager.java:37)
	at jdk.internal.reflect.GeneratedConstructorAccessor47.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:876)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:37)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:595)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:569)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getInstance(CodeStyleSettingsManager.java:102)
	at com.intellij.application.options.CodeStyle.getSettings(CodeStyle.java:57)
	at org.editorconfig.configmanagement.ConfigEncodingManager.getEncoding(ConfigEncodingManager.java:40)
	at com.intellij.openapi.vfs.encoding.EncodingProjectManagerImpl.getEncoding(EncodingProjectManagerImpl.java:190)
	at com.intellij.openapi.vfs.encoding.EncodingManagerImpl.getEncoding(EncodingManagerImpl.java:243)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.getDefaultCharsetFromEncodingManager(LoadTextUtil.java:271)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.guessFromContent(LoadTextUtil.java:329)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.detectHardCharset(LoadTextUtil.java:249)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.detectInternalCharsetAndSetBOM(LoadTextUtil.java:281)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.detectCharsetAndSetBOM(LoadTextUtil.java:265)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.lambda$contentsToByteArray$0(VirtualFileImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:137)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:118)
	at com.intellij.openapi.vfs.VfsUtilCore.loadBytes(VfsUtilCore.java:384)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.computeCharset(VirtualFileSystemEntry.java:463)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getCharset(VirtualFileSystemEntry.java:445)
	at com.intellij.openapi.vfs.VfsUtilCore.loadText(VfsUtilCore.java:376)
	at com.intellij.openapi.vfs.VfsUtilCore.loadText(VfsUtilCore.java:372)
	at com.intellij.javascript.nodejs.PackageJsonData.loadText(PackageJsonData.java:550)
	at com.intellij.javascript.nodejs.PackageJsonData.doParse(PackageJsonData.java:532)
	at com.intellij.javascript.nodejs.PackageJsonData.lambda$getOrCreate$19(PackageJsonData.java:513)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.javascript.nodejs.PackageJsonData.getOrCreate(PackageJsonData.java:503)
	at com.intellij.javascript.nodejs.library.NodeModulesLibraryDirectory$PackageJsonFiles.lambda$new$0(NodeModulesLibraryDirectory.java:523)
	at com.intellij.openapi.project.ProjectLocator.computeWithPreferredProject(ProjectLocator.java:61)
	at com.intellij.javascript.nodejs.library.NodeModulesLibraryDirectory$PackageJsonFiles.lambda$new$1(NodeModulesLibraryDirectory.java:522)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1851)
	at com.intellij.javascript.nodejs.library.NodeModulesLibraryDirectory$PackageJsonFiles.<init>(NodeModulesLibraryDirectory.java:521)
	at com.intellij.javascript.nodejs.library.NodeModulesLibraryDirectory.doCreateLibrary(NodeModulesLibraryDirectory.java:119)
	at com.intellij.javascript.nodejs.library.NodeModulesLibraryDirectory.createLibrary(NodeModulesLibraryDirectory.java:107)
	at com.intellij.javascript.nodejs.library.NodeModulesLibraryDirectory.getLibrary(NodeModulesLibraryDirectory.java:95)
	at com.intellij.javascript.nodejs.library.NodeModulesSyntheticLibraryProvider.lambda$computeRoots$2(NodeModulesSyntheticLibraryProvider.java:29)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1934)
	at com.intellij.javascript.nodejs.library.NodeModulesSyntheticLibraryProvider.computeRoots(NodeModulesSyntheticLibraryProvider.java:25)
	at com.intellij.javascript.nodejs.library.NodeModulesSyntheticLibraryProvider.lambda$getAdditionalProjectLibraries$0(NodeModulesSyntheticLibraryProvider.java:18)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.javascript.nodejs.library.NodeModulesDirectoryManager.computeFileIndexExtensionPreventingRecursion(NodeModulesDirectoryManager.java:205)
	at com.intellij.javascript.nodejs.library.NodeModulesSyntheticLibraryProvider.getAdditionalProjectLibraries(NodeModulesSyntheticLibraryProvider.java:18)
	at com.intellij.openapi.roots.impl.RootIndex.buildRootInfo(RootIndex.java:260)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:72)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:56)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:172)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:155)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:182)
	at com.intellij.openapi.roots.impl.FileIndexBase.getInfoForFileOrDirectory(FileIndexBase.java:96)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getInfoForFileOrDirectory(ProjectFileIndexImpl.java:27)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:140)
	at com.intellij.lang.javascript.library.JSLibraryUtil.getContentRootForFile(JSLibraryUtil.java:341)
	at com.intellij.lang.javascript.library.JSLibraryUtil.getContentRootForFile(JSLibraryUtil.java:333)
	at com.intellij.lang.javascript.buildTools.base.JsbtUtil.getRelativePath(JsbtUtil.java:190)
	at com.intellij.lang.javascript.buildTools.base.JsbtUtil.getRelativePath(JsbtUtil.java:184)
	at com.intellij.lang.javascript.buildTools.npm.NpmTaskTreeView.customizeCell(NpmTaskTreeView.java:87)
	at com.intellij.lang.javascript.buildTools.base.JsbtTaskTreeView$JsbtTreeCellRenderer.customizeCellRenderer(JsbtTaskTreeView.java:907)
	at com.intellij.ui.ColoredTreeCellRenderer.rendererComponentInner(ColoredTreeCellRenderer.java:122)
	at com.intellij.ui.ColoredTreeCellRenderer.getTreeCellRendererComponent(ColoredTreeCellRenderer.java:54)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRenderer(DefaultTreeUI.java:177)
	at com.intellij.ui.tree.ui.DefaultTreeUI$2.getNodeDimensions(DefaultTreeUI.java:479)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:493)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1465)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1272)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.ensurePathIsExpanded(VariableHeightLayoutCache.java:967)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.setExpandedState(VariableHeightLayoutCache.java:181)
	at com.intellij.ui.tree.ui.DefaultTreeUI$3.setExpandedState(DefaultTreeUI.java:511)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.updateExpandedDescendants(BasicTreeUI.java:1975)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeExpanded(BasicTreeUI.java:4212)
	at java.desktop/javax.swing.JTree.fireTreeExpanded(JTree.java:2801)
	at java.desktop/javax.swing.JTree.setExpandedState(JTree.java:3652)
	at java.desktop/javax.swing.JTree.expandPath(JTree.java:2244)
	at com.intellij.lang.javascript.buildTools.base.JsbtTaskTreeView.expandNode(JsbtTaskTreeView.java:579)
	at com.intellij.lang.javascript.buildTools.base.JsbtTaskTreeView.setBuildfileChildren(JsbtTaskTreeView.java:481)
	at com.intellij.lang.javascript.buildTools.base.JsbtTaskTreeView.addBuildfile(JsbtTaskTreeView.java:386)
	at com.intellij.lang.javascript.buildTools.base.JsbtTaskTreeView.init(JsbtTaskTreeView.java:100)
	at com.intellij.lang.javascript.buildTools.base.JsbtToolWindowManager.doCreateToolWindowContent(JsbtToolWindowManager.java:75)
	at com.intellij.lang.javascript.buildTools.base.JsbtToolWindowManager$1.createToolWindowContent(JsbtToolWindowManager.java:62)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:542)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:521)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1033)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:979)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow(ToolWindowManagerImpl.kt:681)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$default(ToolWindowManagerImpl.kt:659)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:2052)
	at com.intellij.openapi.wm.impl.StripeButton.lambda$new$0(StripeButton.java:68)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at com.intellij.openapi.wm.impl.StripeButton.processMouseEvent(StripeButton.java:329)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2790)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.intellij.application.options.IndentOptionsEditorBase PluginClassLoader(plugin=PluginDescriptor(name=BashSupport Pro, id=pro.bashsupport, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/213.5744.224.plugins/bashsupport-pro, version=2.0.6.213, package=null, isBundled=false), packagePrefix=null, instanceId=108, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

**Comment by jansorg** [comment]
Thanks for reporting! I'll investigate and fix asap

**Comment by jansorg** [comment]
@mrbscreen Were you seeing this when opening settings or even at startup? I'm currently only seeing a possible cause related to settings.

**Comment by mrbscreen** [comment]
I choose a project at startup in the "Welcome to WebStorm" Dialog, after that the IDE opens but without any Window in it.

In this Issue you can see screenshots and the log from WebStorm: https://youtrack.jetbrains.com/issue/WEB-53773

**Comment by jansorg** [comment]
Thanks! I found a fix and will publish an update in the next hour.

**Comment by mrbscreen** [comment]
The fix works. Thank you!
